# provde list of apps to scrap
# Go to google playstore and find the package name of app from URI
# and then add it to the list here
Apps:
  google_drive :
    package_name : com.google.android.apps.docs #Google Drive
    geographies_languages:
      #country,lang
      - us, en
      - in, en
